#!/usr/bin/env bash
# FizzBuzz challenge
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

i=1
while ((i<=100))
do
  if (((i % 3 == 0) && (i % 5 == 0)))
  then
      echo "FizzBuzz"
  elif ((i % 3 == 0))
  then
      echo "Fizz"
  elif ((i % 5 == 0))
  then
      echo "Buzz"
  elif (((i % 3 == 0) && (i % 5 == 0)))
  then
      echo "FizzBuzz"
  else
      echo "$i"
  fi
  (("i += 1"))
done
