#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times
# Using while loop only

i="$i"
while ((i<10))
do
  if ((i == 9))
  then
      echo "Hi"
  fi
  echo "Best School"
  (("i += 1"))
done
