#!/usr/bin/env bash
# Bash script that displays "bad luck" of cultures
# Using while loop only and case statement

i=1
while ((i<=20))
do
  echo "$i"
  case $i in
  "4") echo "bad luck from China";;
  "9") echo "bad luck from Japan";;
  "17") echo "bad luck from Italy";;
  esac
  (("i += 1"))
done
