#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
#
# Displays hours from 0 t0 12
# Displays minute from 1 to 59
# Using while loop only

hour=0

while ((hour<=12))
do
  echo "Hour: $hour"

  minute=1
  while ((minute<=59))
  do
    echo "$minute"
    (("minute += 1"))
  done

  (("hour += 1"))
done
