#!/usr/bin/env bash
# Bash script that displays current directory
# +In a list format
# +only the part of the name after the first dash is displayed
#
# Using for loop only

LIST=$("ls")
for list in $LIST;
do
  echo "$list" | cut -d '-' -f2
done
